language: node_js
node_js:
  - 16
# branches:
#   only:
#     - main
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
  # Netlify
  ##
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ $TRAVIS_BRANCH != "main" ]; then
      yarn global add netlify-cli
      # bash _build_scripts/publish-to-netlify.sh
      source _build_scripts/publish-to-netlify.sh

      source _build_scripts/slack-find-author.sh
      source _build_scripts/slack-netlify-message.sh

      yarn global add linkinator
      source _build_scripts/verify-links.sh
    fi
  ##
  # End Netlify
  - echo "I guess I will continue now..."