language: node_js
node_js:
  - 16
# branches:
#   only:
#     - main
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build

  ##
  # Cloud Bucket
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      if [ $TRAVIS_BRANCH = "docusaurus-migration" ]; then
        # unpack secrets
        openssl aes-256-cbc -K $encrypted_617a65259523_key -iv $encrypted_617a65259523_iv -in key.master.json.enc -out key.master.json -d
        # Install gcloud
        gcloud version || true
        if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        echo "LOAD SOURCE"
        source /home/travis/google-cloud-sdk/path.bash.inc
        gcloud version
        gcloud auth activate-service-account --key-file key.master.json
        rm key.master.json
        # set project
        gcloud config set project "$GS_PROJECT"
        # rm everything
        gsutil -m rm -r gs://$GS_BUCKET_WEAVIATE_IO/**
        # cd into assets dir
        cd build/
        # Upload data to bucket
        gsutil -m -h "Cache-Control:public,max-age=3600" cp -r ./ gs://$GS_BUCKET_WEAVIATE_IO/
        # set access
        gsutil iam ch allUsers:objectViewer gs://$GS_BUCKET_WEAVIATE_IO
        # set web service
        gsutil web set -m index.html -e 404.html gs://$GS_BUCKET_WEAVIATE_IO
        # Invalidate the CDN
        gcloud compute url-maps invalidate-cdn-cache $GS_BUCKET_WEAVIATE_IO --path "/*" --async
        # Send sitemap to Google
        curl https://www.google.com/ping?sitemap=https://weaviate.io/sitemap.xml
        # back to root
        cd ..
      fi
    fi
    # End Cloud Bucket
    ##

  ##
  # Netlify
  - |
    yarn global add netlify-cli
    source _build_scripts/publish-to-netlify.sh
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ $TRAVIS_BRANCH != "main" ]; then
      source _build_scripts/slack-find-author.sh
      source _build_scripts/slack-netlify-message.sh
    fi
  # End Netlify
  ##

  ##
  # Link Validation
  - |
    yarn global add linkinator
    source _build_scripts/verify-links.sh
  # End Link Validation
  ##
  
  - echo "It is all done"