language: node_js
node_js:
  - 16
# branches:
#   only:
#     - main
cache:
  yarn: true
  directories:
    - $HOME/google-cloud-sdk
install:
  - yarn install
script:
  - yarn build

  ##
  # Cloud Bucket
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      if [ $TRAVIS_BRANCH = "docusaurus-migration" ]; then
        source _build_scripts/gcp-bucket.sh
      fi
    fi
    # End Cloud Bucket
    ##

  ##
  # Netlify
  - |
    yarn global add netlify-cli
    source _build_scripts/publish-to-netlify.sh
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ $TRAVIS_BRANCH != "main" ]; then
      source _build_scripts/slack-find-author.sh
      source _build_scripts/slack-netlify-message.sh
    fi
  # End Netlify
  ##

  ##
  # Link Validation
  - |
    yarn global add linkinator
    source _build_scripts/verify-links.sh
  # End Link Validation
  ##
  
  - echo "It is all done"